const constants = {
  ADD_PRODUCT_SUCCESS: "ADD_PRODUCT_SUCCESS",
  PRODUCT_FAILED: "PRODUCT_FAILED",
  DISMISS_MESSAGE: "DISMISS_MESSAGE",
  CHANGE_FILTER_BY_KEY_WORD: "CHANGE_FILTER_BY_KEY_WORD",
  CHANGE_SORTED_BY: "CHANGE_SORTED_BY",
  CHANGE_SORTED_BY_DIRECTION: "CHANGE_SORTED_BY_DIRECTION",
  TOGGLE_ONLY_ME: "TOGGLE_ONLY_ME",
  CHANGE_ACTIVE_PAGE: "CHANGE_ACTIVE_PAGE",
};
export default constants;
